name = "yata"
default_targets = ["win32", "win64", "appimage", "lovejs"]
build_directory = "build"
icon_file = "icon.png"

love_files = [
    "+*",
    "-*/.*",
    "::git-ls-tree::",
    "-*/.*",
]

[archive_files]
"README.md" = "README.md"
"LICENSE" = "LICENSE"

[linux.desktop_file_metadata]
Comment="yet another todo list"
Categories="Development;Office"
